const mongoose = require("mongoose");

/**
 * User Vision Board Schema
 * Simple gallery with max 3 images per user
 * Supports multi-tier storage and optimized formats
 */
const userVisionBoardSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
    unique: true, // One gallery per user
  },

  // User's images (max 3)
  images: [
    {
      // Original image
      original: {
        url: { type: String, required: true },
        publicId: { type: String, required: true },
        width: { type: Number },
        height: { type: Number },
        format: { type: String },
        size: { type: Number }, // bytes
      },

      // Optimized versions (auto-generated by Cloudinary)
      optimized: {
        // Web version (compressed, webp)
        web: { type: String },
        // Mobile version (smaller, compressed)
        mobile: { type: String },
        // Thumbnail (small preview)
        thumbnail: { type: String },
      },

      // Image metadata
      title: {
        type: String,
        default: "",
        maxlength: 100,
      },

      description: {
        type: String,
        default: "",
        maxlength: 500,
      },

      // Display order (1, 2, or 3)
      order: {
        type: Number,
        min: 1,
        max: 3,
      },

      uploadedAt: {
        type: Date,
        default: Date.now,
      },
    },
  ],

  // Gallery settings
  settings: {
    backgroundColor: {
      type: String,
      default: "#ffffff",
    },
    layout: {
      type: String,
      enum: ["grid", "carousel", "masonry"],
      default: "grid",
    },
    showTitles: {
      type: Boolean,
      default: true,
    },
  },

  createdAt: {
    type: Date,
    default: Date.now,
  },

  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

// Ensure max 3 images
userVisionBoardSchema.pre("save", function (next) {
  if (this.images && this.images.length > 3) {
    return next(new Error("Maximum 3 images allowed per user"));
  }
  this.updatedAt = Date.now();
  next();
});

// Index for fast user lookup
userVisionBoardSchema.index({ userId: 1 });

module.exports = mongoose.model("UserVisionBoard", userVisionBoardSchema);
