const axios = require('axios');
const dotenv = require('dotenv');
dotenv.config();

const generateCareerIntelligence = async (prompt) => {
    try {
        const response = await axios.post(
            'https://api.anthropic.com/v1/messages',
            {
                model: "claude-3-5-sonnet-20241022",
                max_tokens: 4000,
                messages: [{ role: 'user', content: prompt }]
            },
            {
                headers: {
                    'x-api-key': process.env.ANTHROPIC_API_KEY,
                    'anthropic-version': '2023-06-01',
                    'content-type': 'application/json'
                }
            }
        );

        return response.data.content[0].text;
    } catch (error) {
        console.error('AI Intelligence Generation Error:', error.response ? error.response.data : error.message);
        throw new Error('Failed to generate career intelligence');
    }
};

const enhanceWithAI = async (studentData, baseAnalysis) => {
    const anthropicKey = (process.env.ANTHROPIC_API_KEY || '').trim();
    if (!anthropicKey) {
        console.warn('⚠️ ANTHROPIC_API_KEY not found in .env. Returning static data.');
        return baseAnalysis; // Fall back to static data cleanly if no key
    }

    try {
        console.log('🤖 Sending request to Claude to generate real market data...');
        const prompt = `You are an elite Career Intelligence API specializing in the Indian tech market. 
Below is a student profile and a base JSON structure generated by our rule engine.
Your task is to populate the generic placeholder strings in this JSON with highly specific, accurate, and realistic data.

Student Profile:
- Degree: ${studentData.education?.degreeGroup || 'Unknown'} in ${studentData.education?.specialisation || 'Unknown'}
- Skills: ${(studentData.skills || []).map(s => s.name || s).join(', ')}
- Target Primary Role: ${studentData.preferences?.primary?.role || 'Unknown'}

Return the EXACT SAME JSON structure, but rewrite the generic text values in the following areas with high-quality real descriptions:
1. In primary, secondary, and tertiary objects:
   - tab1: Enhance 'role_description', 'narrative_para1' (What This Role Does), 'narrative_para2' (AI Evolution), and 'narrative_para3' (Who Should Consider) to be world-class, specific, and detailed based on the target role. Replace 'typical_employers_india' with 4-5 real companies. Update 'common_entry_paths', 'job_demand', 'salary_range' (in INR formatted as "X-Y LPA"), and 'ai_impact'. Update 'emerging_roles' with real upcoming titles.
   - tab5: Make 'future_scope', 'target_audience', and 'growth_trajectory' highly detailed and realistic.
2. In combined_tab4:
   - 'combined_pathway_summary'
   - 'learning_roadmap': Ensure titles and descriptions match exactly what is needed given the missing skills in the JSON.
   - 'certifications': Real industry standard certs like AWS Solutions Architect, Google Data Engineer, etc.
   - 'free_courses': Real course titles from YouTube or Coursera.
   - 'projects': Provide 2 or 3 highly realistic, impressive portfolio project ideas with specific scopes.

Output ONLY valid JSON matching this schema, without any intro text or markdown blocks at all. Output pure JSON. Ensure ALL keys from the base JSON are strictly preserved in the final output.

Base JSON to update: 
${JSON.stringify(baseAnalysis)}`;

        const response = await axios.post(
            'https://api.anthropic.com/v1/messages',
            {
                model: "claude-3-5-sonnet-20241022",
                max_tokens: 8000,
                messages: [{ role: 'user', content: prompt }]
            },
            {
                headers: {
                    'x-api-key': anthropicKey,
                    'anthropic-version': '2023-06-01',
                    'content-type': 'application/json'
                },
                timeout: 30000 // 30 second timeout for AI generation
            }
        );

        let textRes = response.data.content[0].text;
        // Clean up markdown block if Claude adds it
        textRes = textRes.replace(/^```json/mi, '').replace(/```$/m, '').trim();
        const enhancedData = JSON.parse(textRes);
        
        console.log('✅ Claude successfully enhanced the analysis with real data!');
        
        // --- DEFENSIVE MERGING ---
        // We merge Claude's enhancement back into the base baseAnalysis to ensure no keys are lost
        // (especially the narrative_para1/2/3 fields which are critical for the dashboard panels)
        const finalData = { ...baseAnalysis, ...enhancedData };

        // Ensure sub-objects are also merged if Claude only returned partial updates
        // --- DEFENSIVE MERGING FOR ROLES ---
        ['primary', 'secondary', 'tertiary'].forEach(key => {
            if (baseAnalysis[key]) {
                const enhRole = enhancedData[key] || {};
                const baseTab1 = baseAnalysis[key].tab1 || {};
                const enhTab1 = enhRole.tab1 || {};

                finalData[key] = {
                    ...baseAnalysis[key],
                    ...enhRole,
                    tab1: { 
                        ...baseTab1,
                        // Only adopt enhanced narrative if it's a valid non-empty string
                        narrative_para1: (enhTab1.narrative_para1 && enhTab1.narrative_para1.length > 20) ? enhTab1.narrative_para1 : baseTab1.narrative_para1,
                        narrative_para2: (enhTab1.narrative_para2 && enhTab1.narrative_para2.length > 20) ? enhTab1.narrative_para2 : baseTab1.narrative_para2,
                        narrative_para3: (enhTab1.narrative_para3 && enhTab1.narrative_para3.length > 20) ? enhTab1.narrative_para3 : baseTab1.narrative_para3,
                        role_name: enhTab1.role_name || baseTab1.role_name,
                        typical_employers_india: enhTab1.typical_employers_india || baseTab1.typical_employers_india
                    },
                    tab3: { ...(baseAnalysis[key].tab3 || {}), ...(enhRole.tab3 || {}) },
                    tab5: { ...(baseAnalysis[key].tab5 || {}), ...(enhRole.tab5 || {}) }
                };
            }
        });

        // --- DEFENSIVE MERGING FOR TAB 4 (ROADMAP) ---
        if (baseAnalysis.combined_tab4 && enhancedData.combined_tab4) {
            finalData.combined_tab4 = {
                ...baseAnalysis.combined_tab4,
                ...enhancedData.combined_tab4,
                // Ensure array structures are preserved
                learning_roadmap: (enhancedData.combined_tab4.learning_roadmap && enhancedData.combined_tab4.learning_roadmap.length > 0) 
                    ? enhancedData.combined_tab4.learning_roadmap 
                    : baseAnalysis.combined_tab4.learning_roadmap,
                projects: (enhancedData.combined_tab4.projects && enhancedData.combined_tab4.projects.length > 0)
                    ? enhancedData.combined_tab4.projects 
                    : baseAnalysis.combined_tab4.projects
            };
        }

        return finalData;
    } catch (error) {
        console.error('❌ AI Enhancement Error:', error.response?.data || error.message);
        console.log('Falling back to deterministic rule engine data.');
        return baseAnalysis;
    }
};

module.exports = { generateCareerIntelligence, enhanceWithAI };
